/* 
 * Leap Play
 *
 * Learn more at https://www.leap-play.com
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = LeapPlay.Api.Client.SwaggerDateConverter;

namespace LeapPlay.Api.Model
{
    /// <summary>
    /// RequestStationQrCode
    /// </summary>
    [DataContract]
    public partial class RequestStationQrCode :  IEquatable<RequestStationQrCode>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RequestStationQrCode" /> class.
        /// </summary>
        /// <param name="qrCode">qrCode.</param>
        public RequestStationQrCode(string qrCode = default(string))
        {
            this.QrCode = qrCode;
        }
        
        /// <summary>
        /// Gets or Sets QrCode
        /// </summary>
        [DataMember(Name="qrCode", EmitDefaultValue=false)]
        public string QrCode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RequestStationQrCode {\n");
            sb.Append("  QrCode: ").Append(QrCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RequestStationQrCode);
        }

        /// <summary>
        /// Returns true if RequestStationQrCode instances are equal
        /// </summary>
        /// <param name="input">Instance of RequestStationQrCode to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RequestStationQrCode input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.QrCode == input.QrCode ||
                    (this.QrCode != null &&
                    this.QrCode.Equals(input.QrCode))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.QrCode != null)
                    hashCode = hashCode * 59 + this.QrCode.GetHashCode();
                return hashCode;
            }
        }
    }

}
