/* 
 * Leap Play
 *
 * Learn more at https://www.leap-play.com
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = LeapPlay.Api.Client.SwaggerDateConverter;

namespace LeapPlay.Api.Model
{
    /// <summary>
    /// RequestTokenRefresh
    /// </summary>
    [DataContract]
    public partial class RequestTokenRefresh :  IEquatable<RequestTokenRefresh>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RequestTokenRefresh" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RequestTokenRefresh() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RequestTokenRefresh" /> class.
        /// </summary>
        /// <param name="refreshToken">refreshToken (required).</param>
        public RequestTokenRefresh(string refreshToken = default(string))
        {
            // to ensure "refreshToken" is required (not null)
            if (refreshToken == null)
            {
                throw new InvalidDataException("refreshToken is a required property for RequestTokenRefresh and cannot be null");
            }
            else
            {
                this.RefreshToken = refreshToken;
            }
        }
        
        /// <summary>
        /// Gets or Sets RefreshToken
        /// </summary>
        [DataMember(Name="refreshToken", EmitDefaultValue=false)]
        public string RefreshToken { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RequestTokenRefresh {\n");
            sb.Append("  RefreshToken: ").Append(RefreshToken).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RequestTokenRefresh);
        }

        /// <summary>
        /// Returns true if RequestTokenRefresh instances are equal
        /// </summary>
        /// <param name="input">Instance of RequestTokenRefresh to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RequestTokenRefresh input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.RefreshToken == input.RefreshToken ||
                    (this.RefreshToken != null &&
                    this.RefreshToken.Equals(input.RefreshToken))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.RefreshToken != null)
                    hashCode = hashCode * 59 + this.RefreshToken.GetHashCode();
                return hashCode;
            }
        }
    }

}
