/* 
 * Leap Play
 *
 * Learn more at https://www.leap-play.com
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = LeapPlay.Api.Client.SwaggerDateConverter;

namespace LeapPlay.Api.Model
{
    /// <summary>
    /// RequestEmailConfirmation
    /// </summary>
    [DataContract]
    public partial class RequestEmailConfirmation :  IEquatable<RequestEmailConfirmation>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RequestEmailConfirmation" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RequestEmailConfirmation() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RequestEmailConfirmation" /> class.
        /// </summary>
        /// <param name="username">username (required).</param>
        /// <param name="emailConfirmationToken">emailConfirmationToken (required).</param>
        public RequestEmailConfirmation(string username = default(string), string emailConfirmationToken = default(string))
        {
            // to ensure "username" is required (not null)
            if (username == null)
            {
                throw new InvalidDataException("username is a required property for RequestEmailConfirmation and cannot be null");
            }
            else
            {
                this.Username = username;
            }
            // to ensure "emailConfirmationToken" is required (not null)
            if (emailConfirmationToken == null)
            {
                throw new InvalidDataException("emailConfirmationToken is a required property for RequestEmailConfirmation and cannot be null");
            }
            else
            {
                this.EmailConfirmationToken = emailConfirmationToken;
            }
        }
        
        /// <summary>
        /// Gets or Sets Username
        /// </summary>
        [DataMember(Name="username", EmitDefaultValue=false)]
        public string Username { get; set; }

        /// <summary>
        /// Gets or Sets EmailConfirmationToken
        /// </summary>
        [DataMember(Name="emailConfirmationToken", EmitDefaultValue=false)]
        public string EmailConfirmationToken { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RequestEmailConfirmation {\n");
            sb.Append("  Username: ").Append(Username).Append("\n");
            sb.Append("  EmailConfirmationToken: ").Append(EmailConfirmationToken).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RequestEmailConfirmation);
        }

        /// <summary>
        /// Returns true if RequestEmailConfirmation instances are equal
        /// </summary>
        /// <param name="input">Instance of RequestEmailConfirmation to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RequestEmailConfirmation input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Username == input.Username ||
                    (this.Username != null &&
                    this.Username.Equals(input.Username))
                ) && 
                (
                    this.EmailConfirmationToken == input.EmailConfirmationToken ||
                    (this.EmailConfirmationToken != null &&
                    this.EmailConfirmationToken.Equals(input.EmailConfirmationToken))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Username != null)
                    hashCode = hashCode * 59 + this.Username.GetHashCode();
                if (this.EmailConfirmationToken != null)
                    hashCode = hashCode * 59 + this.EmailConfirmationToken.GetHashCode();
                return hashCode;
            }
        }
    }

}
