/* 
 * Leap Play
 *
 * Learn more at https://www.leap-play.com
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = LeapPlay.Api.Client.SwaggerDateConverter;

namespace LeapPlay.Api.Model
{
    /// <summary>
    /// StationCurrentState
    /// </summary>
    [DataContract]
    public partial class StationCurrentState :  IEquatable<StationCurrentState>
    {
        /// <summary>
        /// Defines ControlMode
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ControlModeEnum
        {
            
            /// <summary>
            /// Enum Undefined for value: Undefined
            /// </summary>
            [EnumMember(Value = "Undefined")]
            Undefined = 1,
            
            /// <summary>
            /// Enum Local for value: Local
            /// </summary>
            [EnumMember(Value = "Local")]
            Local = 2,
            
            /// <summary>
            /// Enum Remote for value: Remote
            /// </summary>
            [EnumMember(Value = "Remote")]
            Remote = 3,
            
            /// <summary>
            /// Enum RemoteWithQrCode for value: RemoteWithQrCode
            /// </summary>
            [EnumMember(Value = "RemoteWithQrCode")]
            RemoteWithQrCode = 4
        }

        /// <summary>
        /// Gets or Sets ControlMode
        /// </summary>
        [DataMember(Name="controlMode", EmitDefaultValue=false)]
        public ControlModeEnum? ControlMode { get; set; }
        /// <summary>
        /// Defines NetworkState
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum NetworkStateEnum
        {
            
            /// <summary>
            /// Enum Disconnected for value: Disconnected
            /// </summary>
            [EnumMember(Value = "Disconnected")]
            Disconnected = 1,
            
            /// <summary>
            /// Enum Connecting for value: Connecting
            /// </summary>
            [EnumMember(Value = "Connecting")]
            Connecting = 2,
            
            /// <summary>
            /// Enum Connected for value: Connected
            /// </summary>
            [EnumMember(Value = "Connected")]
            Connected = 3
        }

        /// <summary>
        /// Gets or Sets NetworkState
        /// </summary>
        [DataMember(Name="networkState", EmitDefaultValue=false)]
        public NetworkStateEnum? NetworkState { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="StationCurrentState" /> class.
        /// </summary>
        /// <param name="stationId">stationId.</param>
        /// <param name="displayName">displayName.</param>
        /// <param name="controlMode">controlMode.</param>
        /// <param name="networkState">networkState.</param>
        /// <param name="session">session.</param>
        public StationCurrentState(Guid? stationId = default(Guid?), string displayName = default(string), ControlModeEnum? controlMode = default(ControlModeEnum?), NetworkStateEnum? networkState = default(NetworkStateEnum?), Session session = default(Session))
        {
            this.StationId = stationId;
            this.DisplayName = displayName;
            this.ControlMode = controlMode;
            this.NetworkState = networkState;
            this.Session = session;
        }
        
        /// <summary>
        /// Gets or Sets StationId
        /// </summary>
        [DataMember(Name="stationId", EmitDefaultValue=false)]
        public Guid? StationId { get; set; }

        /// <summary>
        /// Gets or Sets DisplayName
        /// </summary>
        [DataMember(Name="displayName", EmitDefaultValue=false)]
        public string DisplayName { get; set; }



        /// <summary>
        /// Gets or Sets Session
        /// </summary>
        [DataMember(Name="session", EmitDefaultValue=false)]
        public Session Session { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class StationCurrentState {\n");
            sb.Append("  StationId: ").Append(StationId).Append("\n");
            sb.Append("  DisplayName: ").Append(DisplayName).Append("\n");
            sb.Append("  ControlMode: ").Append(ControlMode).Append("\n");
            sb.Append("  NetworkState: ").Append(NetworkState).Append("\n");
            sb.Append("  Session: ").Append(Session).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as StationCurrentState);
        }

        /// <summary>
        /// Returns true if StationCurrentState instances are equal
        /// </summary>
        /// <param name="input">Instance of StationCurrentState to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(StationCurrentState input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.StationId == input.StationId ||
                    (this.StationId != null &&
                    this.StationId.Equals(input.StationId))
                ) && 
                (
                    this.DisplayName == input.DisplayName ||
                    (this.DisplayName != null &&
                    this.DisplayName.Equals(input.DisplayName))
                ) && 
                (
                    this.ControlMode == input.ControlMode ||
                    (this.ControlMode != null &&
                    this.ControlMode.Equals(input.ControlMode))
                ) && 
                (
                    this.NetworkState == input.NetworkState ||
                    (this.NetworkState != null &&
                    this.NetworkState.Equals(input.NetworkState))
                ) && 
                (
                    this.Session == input.Session ||
                    (this.Session != null &&
                    this.Session.Equals(input.Session))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.StationId != null)
                    hashCode = hashCode * 59 + this.StationId.GetHashCode();
                if (this.DisplayName != null)
                    hashCode = hashCode * 59 + this.DisplayName.GetHashCode();
                if (this.ControlMode != null)
                    hashCode = hashCode * 59 + this.ControlMode.GetHashCode();
                if (this.NetworkState != null)
                    hashCode = hashCode * 59 + this.NetworkState.GetHashCode();
                if (this.Session != null)
                    hashCode = hashCode * 59 + this.Session.GetHashCode();
                return hashCode;
            }
        }
    }

}
